name: anitrack
description: An anime and manga tracker
publish_to: "none"

version: 0.1.3+2011

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.6.1
  bloc: ^8.1.4
  bottom_bar: ^2.0.3
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fluttertoast: ^8.2.8
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  jikan_api: ^2.2.1
  json_annotation: ^4.9.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  slang: ^3.31.2
  slang_flutter: ^3.31.0
  sqflite: ^2.3.3+2
  swipeable_tile: ^2.0.1
  url_launcher: ^6.3.0
  xml: ^6.5.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_oss_licenses: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  slang_build_runner: ^3.31.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - LICENSE

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
