name: anitrack
description: An anime tracker
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: 2.1.0
  get_it: ^7.2.0
  jikan_api: ^2.0.0

  swipeable_tile: ^2.0.0+3

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
