name: anitrack
description: An anime and manga tracker
publish_to: 'none'

version: 0.1.3+2010

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  archive: ^3.3.7
  bloc: ^8.1.0
  bottom_bar: ^2.0.3
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  fluttertoast: ^8.2.2
  freezed_annotation: 2.1.0
  get_it: ^7.2.0
  jikan_api: ^2.0.0
  json_annotation: 4.6.0
  path: ^1.8.2
  permission_handler: ^10.4.3
  slang: 3.19.0
  slang_flutter: 3.19.0
  sqflite: ^2.2.4+1
  swipeable_tile: ^2.0.0+3
  url_launcher: ^6.1.8
  xml: ^6.2.2

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_oss_licenses: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  slang_build_runner: 3.19.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
